stages:
  - build
  - test
  - deploy

build-backend:
  stage: build
  tags:
  - gcp-2
  image: maven:3-openjdk-17
  script:
    - cd backend
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar
  only:
    - dev
    - backend-dev

build-frontend:
  stage: build
  tags:
  - gcp-2
  image: node:latest
  script:
    - cd BudgetBasket
    - npm install
    - npm run build --prod
  artifacts:
    paths:
      - BudgetBasket/dist/
  only:
    - dev
    - frontend-dev

test_backend:
  stage: test
  tags:
  - gcp-2
  image: maven:3-openjdk-17
  script:
    - cd backend
    - mvn test
  only:
    - dev
    - backend-dev

deploy:
  stage: deploy
  tags:
  - gcp-2
  script:
    - scp frontend/dist/* $SERVER_USERNAME@$SERVER_HOSTNAME:/home/$SERVER_USERNAME/group15/frontend/
    - scp backend/target/*.jar $SERVER_USERNAME@$SERVER_HOSTNAME:/home/$SERVER_USERNAME/group15/backend/
    - ssh $SERVER_USERNAME@$SERVER_HOSTNAME "sudo systemctl disable group15.service && sudo systemctl stop group15.service && sudo mv /home/$SERVER_USERNAME/group15/frontend/* /var/www/html/ && sudo mv /home/$SERVER_USERNAME/group15/backend/*.jar /opt/group15/group15.jar && sudo systemctl start group15.service && sudo systemctl enable group15.service"
  environment:
    name: production
  only:
    - main
    - dev