stages:
  - build
  - test

build:
  stage: build
  image: maven:latest
  script:
    - cd backend
    - mvn clean package
  only:
    - dev
    - backend-dev

test_backend:
  stage: test
  image: maven:latest
  script:
    - cd backend
    - mvn test
  only:
    - dev
    - backend-dev
